# Generated by Django 3.0.3 on 2020-05-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
    ]
