# Generated by Django 3.0.3 on 2020-05-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_unit',
            field=models.IntegerField(default=0),
        ),
    ]
